# Generated by Django 6.0.2 on 2026-02-17 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('top_clause_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('html_anchor', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='app_shnq.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_model', models.CharField(max_length=100)),
                ('vector', models.JSONField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('shnq_code', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(blank=True, max_length=500, null=True)),
                ('clause_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lex_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='app_shnq.clause')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('lex_url', models.URLField(blank=True, null=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='docs/original/')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='docs/html/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='app_shnq.category')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.AddField(
            model_name='clause',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='app_shnq.document'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='app_shnq.document'),
        ),
        migrations.CreateModel(
            name='NormImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_title', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('appendix_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('html_anchor', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('context_text', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='app_shnq.chapter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_shnq.document')),
            ],
            options={
                'ordering': ('document', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_model', models.CharField(max_length=100)),
                ('vector', models.JSONField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('shnq_code', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(blank=True, max_length=500, null=True)),
                ('appendix_number', models.CharField(blank=True, max_length=30, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='app_shnq.normimage')),
            ],
        ),
        migrations.CreateModel(
            name='NormTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_title', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('table_number', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('html_anchor', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('raw_html', models.TextField(blank=True, default='')),
                ('raw_html_ru', models.TextField(blank=True, default='')),
                ('raw_html_en', models.TextField(blank=True, default='')),
                ('raw_html_ko', models.TextField(blank=True, default='')),
                ('markdown', models.TextField(blank=True, default='')),
                ('markdown_ru', models.TextField(blank=True, default='')),
                ('markdown_en', models.TextField(blank=True, default='')),
                ('markdown_ko', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='app_shnq.chapter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app_shnq.document')),
            ],
            options={
                'ordering': ('document', 'order'),
            },
        ),
        migrations.CreateModel(
            name='NormTableRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app_shnq.normtable')),
            ],
            options={
                'ordering': ('table', 'row_index'),
                'unique_together': {('table', 'row_index')},
            },
        ),
        migrations.CreateModel(
            name='NormTableCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('col_index', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('is_header', models.BooleanField(default=False)),
                ('row_span', models.PositiveIntegerField(default=1)),
                ('col_span', models.PositiveIntegerField(default=1)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='app_shnq.normtablerow')),
            ],
            options={
                'ordering': ('row', 'col_index'),
                'unique_together': {('row', 'col_index')},
            },
        ),
    ]
