# Generated by Django 6.0.2 on 2026-02-18 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRowEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_model', models.CharField(max_length=100)),
                ('vector', models.JSONField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('shnq_code', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(blank=True, max_length=500, null=True)),
                ('table_number', models.CharField(db_index=True, max_length=50)),
                ('table_title', models.CharField(blank=True, max_length=500, null=True)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('search_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='app_shnq.normtablerow')),
            ],
        ),
    ]
